const images = {
  img1: require("../assets/images/img1.jpg"),
  img2: require("../assets/images/img2.jpg"),
  img3: require("../assets/images/img3.jpg"),
  img4: require("../assets/images/img4.jpg"),
  img5: require("../assets/images/img5.jpg"),
  img6: require("../assets/images/img6.jpg"),
  img7: require("../assets/images/img7.jpg"),
  img8: require("../assets/images/img8.jpg"),
  img9: require("../assets/images/img9.jpg"),
  img10: require("../assets/images/img10.jpg"),
  img11: require("../assets/images/img11.jpg"),
  img12: require("../assets/images/img12.jpg"),
  img13: require("../assets/images/img13.jpg"),
  img14: require("../assets/images/img14.jpg"),
  img15: require("../assets/images/img15.jpg"),
  img16: require("../assets/images/img16.jpg"),
  img17: require("../assets/images/img17.jpg"),
  img18: require("../assets/images/img18.jpg"),
  img19: require("../assets/images/img19.jpg"),
  img20: require("../assets/images/img20.jpg"),
  img21: require("../assets/images/img21.jpg"),
  img22: require("../assets/images/img22.jpg"),
  img23: require("../assets/images/img23.jpg"),
  img24: require("../assets/images/img24.jpg"),
  img25: require("../assets/images/img25.jpg"),
  img26: require("../assets/images/img26.jpg"),
  img27: require("../assets/images/img27.jpg"),
  img27: require("../assets/images/img28.jpg"),
  img29: require("../assets/images/img29.jpg"),
  img30: require("../assets/images/img30.jpg"),
};

export default images;
